FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2: Serve the app with nginx
FROM node:20-alpine AS development

WORKDIR /app

COPY --from=builder /app/dist ./dist

RUN npm install serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]